# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: NPM Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # Setup .npmrc file to publish to GitHub Packages
    # - uses: actions/setup-node@v2
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
    # # Publish to GitHub Packages
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Docs Update
  docs-update:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Checkout ArtalkDocs
        uses: actions/checkout@v2
        with:
          repository: ArtalkJS/Docs
          token: ${{ secrets.PAT }}

      - name: Update CDN links
        run: |
          sed -i 's#artalk@.[^/]*#artalk@${{ steps.get_version.outputs.VERSION }}#g' docs/code/ArtalkCDN.json
          sed -i 's#artalk@.[^/]*#artalk@${{ steps.get_version.outputs.VERSION }}#g' docs/code/quick-start/cdn.html

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Artalk CDN link to v${{ steps.get_version.outputs.VERSION }}

